from django.db import models
from django.conf import settings
from django.urls import reverse
from rest_framework.reverse import reverse as api_reverse


# Create your models here.
class Genre(models.Model):
    # Hidden: PK or id. This is auto generated by django when making models
    genre_name = models.CharField(max_length=256, null=False, blank=False)
    parent_id = models.ForeignKey("self", null=True, blank=True)

    def __str__(self):
        return str(self.genre_name)


class PieceType(models.Model):
    # Hidden: PK or id. This is auto generated by django when making models
    piece_type_name = models.CharField(max_length=256, null=True)

    def __str__(self):
        return str(self.piece_type_name)


class PromptPiece(models.Model):
    # Hidden: PK or id. This is auto generated by django when making models
    piece_type = models.ForeignKey("PieceType", )
    piece_genre = models.ForeignKey()
    piece_description = models.CharField()
    piece_name = models.TextField()


class BuiltPrompt(models.Model):
    pass





