# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_auto_20180219_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecetype',
            name='piece_type_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
