# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_piecetype_piece_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptpiece',
            name='piece_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='promptpiece',
            name='piece_genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prompts.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promptpiece',
            name='piece_name',
            field=models.CharField(default='Randy', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promptpiece',
            name='piece_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prompts.PieceType'),
            preserve_default=False,
        ),
    ]
