# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_auto_20180221_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtprompt',
            name='is_wild_card',
            field=models.NullBooleanField(),
        ),
    ]
