# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_builtprompt_is_wild_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtprompt',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_genre', to='prompts.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_parent', to='prompts.Genre'),
        ),
    ]
