# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0008_auto_20180317_1646'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='promptpiece',
            managers=[
                ('randomPieceBy', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='promptpiece',
            name='piece_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
